<?php

/**
 * Implementation of hook_user
 */
function example_user_login(&$edit, $account) {
    drupal_set_message(t('Olá, @name, voce precisa verificar seu inbox', array('@name' => $account->name)));
}

/**
 * Implementation of hook_menu
 */
function example_menu() {
    $items['exemplo'] = array(
        'page callback' => 'exemplo_test_page_callback',
        'access callback' => TRUE,
    );
    $items['testing'] = array(
        'page callback' => 'exemplo_testing_page_callback',
        'access callback' => TRUE,
    );
    return $items;
}

/**
 * Funcao que retorna conteudo para nossa nova pagina,
 * /testing
 */

function exemplo_testing_page_callback(){
    $output = "Agora temos conteudo";
    return $output;
}

/**
 * callback para nossa pagina 
 */
function exemplo_test_page_callback() {
    $output = "Conteudo da página aqui";
    return $output;
}


/**
 * 
 * Implementation of hook_block_info
 */
function example_block_info() {

    $blocks['meubloco'] = array(
        'info' => t('Meu bloco favorito'),
    );
    $blocks['meubloco2'] = array(
        'info' => t('Meu bloco NAO favorito'),
    );

    return $blocks;
}

/**
 * Implementation of hook_block_view
 */

function example_block_view($delta) {

    dsm(debug_backtrace());
    
    drupal_set_message("Drupal esta pedindo o conteudo do block: ".$delta);
    switch ($delta) {

        case 'meubloco':

            $block['subject'] = t('Aqui esta o Favorito');

            $block['content'] = array('#markup' => '<p> Meu <strong>primeiro</strong> bloco </p>');

            return $block;

            break;
        
        case 'meubloco2':

            $block['subject'] = t('Aqui esta o Rejeitado');

            $block['content'] = array('#markup' => '<p> Esqueceram de min</p>');

            return $block;

            break;
    }
}

